### ISSUE TITLE
project compile issue

### ISSUE THREAD

**Issue by abolhasanfathi** [jonathantribouharet/JTScrollViewController#1]
hi
I have a general problem that I don't know how to solve it.
Sometimes when I download other people's projects from internet, I face errors in compile time like this:
![screen shot 2015-01-21 at 10 48 07 am](https://cloud.githubusercontent.com/assets/10627217/5832570/808ea7c4-a15c-11e4-83a9-7a5325782701.png)

I have this errors in JTScrollViewController too.
 (https://github.com/jonathantribouharet/JTScrollViewController)
I tried so hard to solve it but that didn't work...
Can you explain to me what should I do step by step?

**Comment by johnvuko** [comment]
It's probably because i use cocoapod and you didn't use it, so you must have installed the library in a different way. So you can either install the library with Cocoapod or just drag and drop 'JTScrollViewController' in your project (not the project's folder but the folder which contains 2 files JTScrollViewController.h and JTScrollViewController.m).

**Comment by abolhasanfathi** [comment]
Thank you man <3
You are right. It solved. :D
